#!/usr/bin/env bash
# A script that:
# - Installs Nginx
# - Nginx should Listen on port 80.
# - Return a page containing "Hello World" when queried
#   at the root with a curl GET request.

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# configuring nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Creating a sample page
echo "Hello World!" > /var/www/html/index.html

# Start Nginx
service nginx start
