#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

# To install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuring nginx
ufw allow 'Nginx HTTP'

# Creating a sample page
echo 'Hello World!' > /var/www/html/index.html

# Adding some more configuration to the existing server block
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.facebook.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
