#!/usr/bin/env bash
# Displays Best School 10 times, displays hi on the 9th iteration

for i in {1..10}; do
  if [ $i -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
done
